# Generated by Django 5.0 on 2024-02-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KMLData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kml_file', models.FileField(upload_to='kml_files/')),
            ],
        ),
    ]
