# Generated by Django 5.0 on 2024-02-20 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kml_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
            ],
        ),
    ]
